source 'https://rubygems.org'

gem 'rake'

gem 'rack'
gem 'sprockets'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-github'

gem 'coffee-script'

gem 'hikidoc'
gem 'twitter-text', require: false
gem 'pygments.rb'

gem 'thin', require: false
gem 'tdiary-io-rdb'
gem 'pg'

# To use memcached for Cache
# gem 'tdiary-cache-memcached'
