source 'https://rubygems.org'

gem 'rake'

gem 'rack'
gem 'sprockets'
gem 'hikidoc'
gem 'fastimage'

gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-github'

gem 'thin', require: false
gem 'tdiary-io-rdb'
gem 'pg'
gem 'thor'

# To use memcached for Cache
# gem 'tdiary-cache-memcached'
