@preview_label_conf = '日記のプレビュー'
@preview_label_interval = '更新間隔 (秒)'
@preview_label_interval_desc = 'プレビューを表示する間隔を秒単位で指定します。間隔を短くするとよりリアルタイムになりますが、その分サーバーに負荷がかかります。'
@preview_label_min_width = '横並びで表示する画面サイズ (px)'
@preview_label_min_width_desc = 'プレビュー画面を横並びで表示する幅をピクセル単位で指定します。ここで指定した幅より画面サイズが小さい場合は縦に並べて表示します。'
